### ISSUE TITLE
Improve function chaining error messages

### ISSUE THREAD

**Issue by danielpetisme** [golo-lang/golo-lang#262] opened 2015-05-06 21:27 UTC
Considering this snippet
```
module chaining


function main = |args...| {
  let f = |x, y| -> x + y
  let g = |a, b| -> a + b
  let h = f: andThen(g)

  h: invoke(1, 2)
}
```
Obviously the function chain can' t work as is because `g` is expecting 2 args when `f` will return one and only one value. 

The according error message (Which frankly freaked me out!) is:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000144d8ec62, pid=12674, tid=4867
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# j  java.lang.invoke.DirectMethodHandle.internalMemberName(Ljava/lang/Object;)Ljava/lang/Object;+0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/daniel/workspace/golo-temp/hs_err_pid12674.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
[1]    12674 abort      golo golo --files chaining.golo
```

From a user point of view is 1/ scary to see a message raise by the JVM itself 2/ helpless to find  and fix the root problem.

Would be nice to detect such mistakes and warn the developer.

If I'm right the filter function (ie. the `andThen` argument) can have 0 or 1 argument (no more). So we could easily detect that during the invocation of the brand new `FunctionReference`.

**Comment by yloiseau** [comment] 2015-05-07 06:52
the composing functions (this is a function composition, not a filter :p) must have 1 parameter, since they are called with the result of the previous function as argument. This could be checked indeed. 
We could even go farther, by autospreading arguments, such that:
```golo
let f = |x, y| -> [x + y, x - y]
let g = |a, b| -> a + b
let h = f: andThen(g)
require(h(21) == 42, "err")
```
would work; kinda implicit uncurry, but explicit is better than implicit.

**Comment by jponge** [comment] 2015-05-07 07:02
Oh yes we could add a check in andThen()

**Comment by danielpetisme** [comment] 2015-05-07 07:04
Based on [MethodHandles.filterReturnValue](http://docs.oracle.com/javase/7/docs/api/java/lang/invoke/MethodHandles.html#filterReturnValue(java.lang.invoke.MethodHandle,%20java.lang.invoke.MethodHandle)) the target method can return `void` and the chaining can work.

**Comment by jponge** [comment] 2015-05-07 07:05
But method handles always return something, null in case of void.

**Comment by jponge** [comment] 2015-05-07 11:33
I can reproduce the `SIGSEGV` :smile:

**Comment by jponge** [comment] 2015-05-07 11:43
@danielpetisme see #263

**Closed** 2015-05-07 12:09 UTC
Labels: improvement

**Comment by danielpetisme** [comment] 2015-05-07 16:40
@jponge wouldn't be nice to open issue on the official jdk tracker? I don't think the `SIGSEGV` is the expected behavior :wink:

**Comment by jponge** [comment] 2015-05-07 16:48
Oh yes. Do you want to open a bug?

**Comment by danielpetisme** [comment] 2015-05-07 18:08
I'll do it ASAP...
